### ISSUE TITLE
Buildtool tasks run only once when passed multiple times in the run build option

### ISSUE THREAD

**Issue by AsthaSharma86** [mathworks/matlab-circleci-orb#58]
- matlab/run-build:
          tasks: mtest clean mtest
The above script should run mtest clean and mtest. But  it only runs mtest and clean. 

For reference, https://app.circleci.com/pipelines/github/AsthaSharma86/ci-sample-repo/8/workflows/1bf76a57-7606-4cd9-8f54-fb8c9d6796dc/jobs/7

Similarly,
- matlab/run-build:
          tasks: mtest mtest clean mtest
The above script should run mtest, skip mtest, clean and re rerun mtest. But it only runs mtest and clean once. 

For reference, https://app.circleci.com/pipelines/github/AsthaSharma86/ci-sample-repo/7/workflows/522406c2-ee26-4dda-8bf7-edcd6b1cdc67/jobs/6

**Comment by davidbuzinski** [comment]
Hi @AsthaSharma86 

This is in order to work in the same way that `buildtool` invocations work. Each `run-build` is one call to `buildtool`. If you do multiple `run-builds` in sequence with the tasks in the same order specified above you will get the expected results.

For reference, here is the doc for buildtool: https://www.mathworks.com/help/matlab/ref/buildtool.html. It states:
> buildtool [tasks](https://www.mathworks.com/help/matlab/ref/buildtool.html#mw_820c067c-1d35-4064-b2b8-d1f6b9ea9822) runs the specified tasks as well as all the tasks on which they depend. The command runs the tasks in the order specified. It runs each task at most one time and ignores a task in the list that has already run.
